emoji_sentence = input().replace(":)", "🙂").replace(":(", "🙁")
# emoji_sentence = emoji_sentence.replace(":)", "🙂")
# emoji_sentence = emoji_sentence.replace(":(", "🙁")
# emoji_sentence = emoji_sentence.replace(":(", "🙁")
print(emoji_sentence)
